# change the followings to match your Github username and repo name
baseurl: ""
url: "https://ctsetera.dev" # the url of your github pages

# site information used in page title, meta data etc.
title: "ctsetera.dev"
description: ctsetera.dev

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: めゆう
author-bio: false # change to false to hide
author-image: icon.png # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
  - text: About
    permalink: about
  - text: Blog
    permalink: blog

# use false to turn off any social media links
twitter: https://twitter.com/34sj
misskey: https://misskey.io/@ctsetera
facebook: false
instagram: false
github: https://github.com/34sj
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
  - jekyll-seo-tag

collections_dir: .
